function: pad_array
info:
  xsize: 100.0
  ysize: 100.0
module: gdsfactory.components.pad
name: pad_array
settings:
  columns: 6
  orientation: 270
  pad: pad
  rows: 1
  spacing:
  - 150.0
  - 150.0
