function: grating_coupler_elliptical_trenches
info:
  period: 0.6759999999999999
  polarization: te
  wavelength: 1.53
module: gdsfactory.components.grating_coupler_elliptical_trenches
name: grating_coupler_elliptical_trenches_taper_angle35
settings:
  cross_section: xs_sc
  end_straight_length: 0.2
  fiber_angle: 15.0
  grating_line_width: 0.343
  layer_trench: SHALLOW_ETCH
  n_periods: 30
  ncladding: 1.443
  neff: 2.638
  p_start: 26
  polarization: te
  taper_angle: 35
  taper_length: 16.6
  trenches_extra_angle: 9.0
  wavelength: 1.53
