function: add_trenches
info:
  dy: 10.0
  length: 16.637
  radius: 10.0
  radius_min: 7.061
  route_info_length: 16.637
  route_info_n_bend_90: 1.0
  route_info_type: xs_sc
  route_info_weight: 16.637
  route_info_xs_sc_length: 16.637
  width: 0.5
module: gdsfactory.components.add_trenches
name: bend_euler_add_trenches_cb24b746
settings:
  bot: true
  component:
    function: bend_euler
  cross_section: xs_rc_with_trenches
  layer_trench:
  - 3
  - 6
  left: false
  right: true
  top: false
  width_trench: 3
