function: taper
info:
  length: 100.0
  width1: 0.5
  width2: 0.2
module: gdsfactory.components.taper
name: taper_length100_width20p2
settings:
  cross_section: xs_sc
  length: 100
  port: null
  port_order_name:
  - o1
  - o2
  port_order_types:
  - optical
  - optical
  width1: 0.5
  width2: 0.2
  with_two_ports: true
