function: pad_array
info:
  xsize: 100.0
  ysize: 100.0
module: gdsfactory.components.pad
name: pad_array_bc0d660e
settings:
  columns: 1
  orientation: 180
  pad: pad
  rows: 3
  spacing:
  - 150.0
  - 150.0
