function: via_corner
info:
  length: 10.0
  size:
  - 10.0
  - 10.0
module: gdsfactory.components.via_corner
name: via_corner
settings:
  cross_section:
  - - function: cross_section
      module: gdsfactory.cross_section
      settings:
        layer: M2
        port_names:
        - e1
        - e2
        port_types:
        - electrical
        - electrical
        radius: null
        width: 10.0
    - - 0
      - 180
  - - function: cross_section
      module: gdsfactory.cross_section
      settings:
        layer: M3
        port_names:
        - e1
        - e2
        port_types:
        - electrical
        - electrical
        radius: null
        width: 10.0
    - - 90
      - 270
  layers_labels:
  - m2
  - m3
  vias:
  - function: via
    module: gdsfactory.components.via
    settings:
      enclosure: 2
      layer: VIA1
