function: compass
info: {}
module: gdsfactory.components.compass
name: compass
settings:
  layer: WG
  port_inclusion: 0.0
  port_orientations:
  - 180
  - 90
  - 0
  - -90
  port_type: electrical
  size:
  - 4.0
  - 2.0
