function: ring_single_bend_coupler
info: {}
module: gdsfactory.components.ring_single_bend_coupler
name: ring_single_bend_coupler
settings:
  bend:
    function: bend_circular
  coupling_angle_coverage: 180.0
  cross_section: xs_sc
  cross_section_inner: xs_sc
  cross_section_outer: xs_sc
  gap: 0.2
  length_x: 0.6
  length_y: 0.6
  radius: 5.0
