function: add_grating_couplers_with_loopback_fiber_single
info:
  length: 9973.393
  polarization: te
  wavelength: 1.53
module: gdsfactory.components.add_grating_couplers
name: spiral_inner_io_fiber_single_add_grating_couplers_with_loopback_fiber_single
settings:
  component: spiral_inner_io_fiber_single
  cross_section:
    function: cross_section
    module: gdsfactory.cross_section
    settings:
      radius: 10
      radius_min: 5
  gc_port_name: o1
  grating_coupler:
    function: grating_coupler_elliptical_trenches
    module: gdsfactory.components.grating_coupler_elliptical_trenches
    settings:
      polarization: te
      taper_angle: 35
  loopback_xspacing: 5.0
  rotation: 90
  select_ports:
    function: select_ports
    module: gdsfactory.port
    settings:
      port_type: optical
  with_loopback: true
