function: mzi_pads_center
info: {}
module: gdsfactory.components.mzi_pads_center
name: mzi_pads_center
settings:
  cross_section: xs_sc
  cross_section_metal: xs_metal_routing
  delta_length: 40.0
  length_x: 500
  length_y: 40
  min_straight_length: 5.0
  mzi:
    function: mzi
  mzi_gnd_bot: bot_r_e2
  mzi_gnd_top: top_l_e2
  mzi_sig_bot: bot_l_e2
  mzi_sig_top: top_r_e2
  pad:
    function: pad
    module: gdsfactory.components.pad
    settings:
      size:
      - 80
      - 80
  pad_gnd_bot: e4_1_2
  pad_gnd_top: e2_1_2
  pad_sig_bot: e1_1_1
  pad_sig_top: e3_1_3
  pad_spacing: pad_spacing
  ps_bot:
    function: straight_heater_metal_undercut
    module: gdsfactory.components.straight_heater_metal
    settings:
      with_undercut: false
  ps_top:
    function: straight_heater_metal_undercut
    module: gdsfactory.components.straight_heater_metal
    settings:
      with_undercut: false
