function: text_rectangular_multi_layer
info: {}
module: gdsfactory.components.text_rectangular
name: text_rectangular_multi_layer
settings:
  layers:
  - WG
  - M1
  - M2
  - MTOP
  text: abcd
  text_factory:
    function: text_rectangular
