function: bezier
info:
  end_angle: 0
  length: 10.226
  min_bend_radius: 10.885
  start_angle: 0
module: gdsfactory.components.bezier
name: bezier
settings:
  bend_radius_error_type: null
  control_points:
  - - 0.0
    - 0.0
  - - 5.0
    - 0.0
  - - 5.0
    - 1.8
  - - 10.0
    - 1.8
  cross_section: xs_sc
  end_angle: null
  npoints: 201
  start_angle: null
  with_manhattan_facing_angles: true
