function: taper_strip_to_ridge_trenches
info: {}
module: gdsfactory.components.taper
name: taper_strip_to_ridge_trenches
settings:
  layer_wg: WG
  length: 10.0
  slab_offset: 3.0
  trench_layer: DEEP_ETCH
  trench_offset: 0.1
  trench_width: 2.0
  width: 0.5
