function: straight
info:
  length: 10.0
  route_info_length: 10.0
  route_info_type: xs_m3
  route_info_weight: 10.0
  route_info_xs_m3_length: 10.0
  width: 10.0
module: gdsfactory.components.straight
name: straight_299ab026
settings:
  cross_section: xs_metal_routing
  length: 10.0
  npoints: 2
