function: greek_cross_with_pads
info: {}
module: gdsfactory.components.greek_cross
name: greek_cross_with_pads
settings:
  greek_cross_component:
    function: greek_cross
  pad:
    function: pad
  pad_spacing: 150.0
  pad_via:
    function: via_stack
    module: gdsfactory.components.via_stack
    settings:
      layers:
      - M1
      - M2
      - MTOP
      vias:
      - function: via
        module: gdsfactory.components.via
        settings:
          enclosure: 2
          layer: VIA1
      - function: via
        module: gdsfactory.components.via
        settings:
          layer: VIA2
      - null
  xs_metal:
    function: cross_section
    module: gdsfactory.cross_section
    settings:
      layer: M1
      port_names:
      - e1
      - e2
      port_types:
      - electrical
      - electrical
      radius: null
      width: 10.0
