function: mzm
info: {}
module: gdsfactory.components.mzm
name: mzm
settings:
  bend:
    function: bend_euler
  combiner: mmi1x2
  cross_section: xs_sc
  delta_length: 0.0
  length_x: 500
  length_y: 2.0
  min_length: 0.01
  mirror_bot: false
  nbends: 2
  phase_shifter:
    function: straight_pin
  port_e0_combiner: o3
  port_e0_splitter: o3
  port_e1_combiner: o2
  port_e1_splitter: o2
  splitter: mmi1x2
  straight:
    function: straight
  with_splitter: true
