name: Test PDKs

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/gdsfactory/gdsfactory7:main
    strategy:
      fail-fast: false
      matrix:
        repo:
          - { owner: "gdsfactory", repo: "cspdk" }
          - { owner: "gdsfactory", repo: "skywater130" }
          - { owner: "gdsfactory", repo: "ubc" }

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Checkout other repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo.owner }}/${{ matrix.repo.repo }}
          path: other-repo

      - name: Run tests
        run: |
          ls other-repo
          pip install -e other-repo
          pip install -e .
          cd other-repo
          pytest
